dist: xenial
language: python
python:
  - "3.7"
before_install:
  - export BOTO_CONFIG=/dev/null
install:
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage --cover-package=batching
after_success:
  - coveralls